language: ruby
rvm:
- 2.1
before_script: npm install
install: bundle install
script: npm run prod
after_success: bundle exec s3_website push
branches:
  only:
  - stable
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: m6izFBiFQVXGTmfU7ZgvwIZlfjf9uGLdK+7VdKFzyPMg/W/v2dHRt2CyGsg2+G30DVTgl+/+Z4nZotSb0WP/ux8jMLsnejwl9wD0vDAEYUuNgb7BIyLGHvhmOvJPKsmjyTKMS+u4rE9Ci+k3suvmQ9TdvWQw67lVKx7XQ367rBk=
  - secure: fOS5eL2VLUV4Wp9dtwPblUNICORy5Hiu5fY4enlc6A+pfIR4byp/kOnX7UoQpY4jFMqQbXdYB8jBtIHXNnr+vkNKma3dXdrLx51uZqh0Ixggptu0rqpIB/tYzUOxMhMLNCta1PTlemVSMXhrzZ6XPQ/YNrVNgA10hFUHvozwlkQ=