language: ruby
rvm:
- 2.1
before_script: npm install
install: bundle install
script: npm run prod
after_success: bundle exec s3_website push
branches:
  only:
  - stable
env:
  global:
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
      - secure: eQ0WnIM1WgT9tMCYUMyigZQzocUJtbe4/T2ZvyJ7ouIBEDkJOg75rOTj24uqCSJ9wDtxSBhsw+TOkfBSPLj89a2inWvFFJo4b5w6ajINMssupxBTvCBHyU7OFpGdSDa7I1j8/aJI9uO+PzU+5NOL8B4qg/UPBE0f9PiXnuKpMiw=
      - secure: ZrPKuJY0EqEV29OKnmxLIQ2n/CXsmpzkS7SvVEBDBbICznS1BbfZe8m741lO74p8ZAvPKqZ9ho7MU8Db0aP1mybRpDdFffBALe68PSROfZqsbR5oVN6uJVJPmSl4QfUfI4c1OMek3ROATCZe5YsLM6bXeDv1cSN56NkURqkr6dA=
